kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-k8s
  template:
    metadata:
      labels:
        app: react-k8s
    spec:
      containers:
      - name: react-k8s
        image: intechpro/react-k8s:latest
        ports:
        - containerPort: 80